name: 'InvisiRisk PSE Action'
description: 'GitHub Action for InvisiRisk PSE integration'
inputs:
  scan_id:
    description: 'Scan ID for the InvisiRisk PSE'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Debug Directory
      shell: sh
      run: |
        echo "Resolved Action Path: ${{ github.action_path }}"
        echo "$GITHUB_ACTION_PATH"
    - name: Check files in action directory using find command
      shell: sh
      run: |
        find $GITHUB_ACTION_PATH -type f

    - name: Run setup script
      shell: sh
      run: |
        chmod +x $GITHUB_ACTION_PATH/scripts/setup.sh
        chmod +x $GITHUB_ACTION_PATH/scripts/cleanup.sh
        $GITHUB_ACTION_PATH/scripts/setup.sh \
          "${{ inputs.scan_id }}" \
          "${{ github.repository }}" \
          "${{ github.run_id }}" \
          "${{ github.run_attempt }}" \
          "${{ github.workflow }}" \
          "${{ github.job }}" \
          "${{ github.sha }}" \
          "${{ github.ref_name }}"

  post:
    - name: Cleanup
      shell: sh
      run: |
        $GITHUB_ACTION_PATH/scripts/cleanup.sh \
          "${{ github.repository }}" \
          "${{ github.run_id }}" \
          "${{ github.run_attempt }}" \
          "${{ github.workflow }}" \
          "${{ github.job }}"
