name: 'InvisiRisk PSE Action'
description: 'GitHub Action for InvisiRisk PSE integration'
inputs:
  scan_id:
    description: 'Scan ID for the InvisiRisk PSE'
    required: true
  package_url:
    description: 'URL to download the package containing denat, PSE proxy, and config files'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Debug Directory
      shell: sh
      run: |
        echo "Resolved Action Path: ${{ github.action_path }}"
        echo "$GITHUB_ACTION_PATH"
    - name: Check files in action directory using find command
      shell: sh
      run: |
        find $GITHUB_ACTION_PATH -type f

    - name: Run setup script
      shell: sh
      run: |
        chmod +x $GITHUB_ACTION_PATH/scripts/setup.sh
        chmod +x $GITHUB_ACTION_PATH/scripts/cleanup.sh
        $GITHUB_ACTION_PATH/scripts/setup.sh \
          "${{ inputs.scan_id }}" \
          "${{ inputs.package_url }}" \
          "${{ github.repository }}" \
          "${{ github.run_id }}" \
          "${{ github.run_attempt }}" \
          "${{ github.workflow }}" \
          "${{ github.job }}" \
          "${{ github.sha }}" \
          "${{ github.ref_name }}"

    - name: Register cleanup
      shell: sh
      run: |
        # Create cleanup script
        echo "#!/bin/sh" > /cleanup.sh
        echo "$GITHUB_ACTION_PATH/scripts/cleanup.sh \
          '${{ github.repository }}' \
          '${{ github.run_id }}' \
          '${{ github.run_attempt }}' \
          '${{ github.workflow }}' \
          '${{ github.job }}'" >> /cleanup.sh
        chmod +x /cleanup.sh
        # Register cleanup to run on exit
        trap "/cleanup.sh" EXIT
