name: 'InvisiRisk PSE Action'
description: 'GitHub Action for InvisiRisk PSE integration'
inputs:
  scan_id:
    description: 'Scan ID for the InvisiRisk PSE'
    required: true
  denat_url:
    description: 'URL to download denat tool'
    required: true
  pse_url:
    description: 'URL to download PSE proxy'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Install curl and wget
      run: apk add --no-cache curl wget
      shell: sh
        
    - name: Run Node.js script
      run: node ${{ github.action_path }}/dist/index.js
      shell: sh
      env:
        INPUT_SCAN_ID: ${{ inputs.scan_id }}
        INPUT_DENAT_URL: ${{ inputs.denat_url }}
        INPUT_PSE_URL: ${{ inputs.pse_url }}
