name: 'InvisiRisk PSE Action'
description: 'GitHub Action for InvisiRisk PSE integration'
inputs:
  scan_id:
    description: 'Scan ID for the InvisiRisk PSE'
    required: true
  denat_url:
    description: 'URL to download denat tool'
    required: true
  pse_url:
    description: 'URL to download PSE proxy'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Debug directory structure
      shell: sh
      run: |
        echo "Current directory: $(pwd)"
        echo "Action path: ${{ github.action_path }}"
        echo "Workspace: ${{ github.workspace }}"
        echo "\nDirectory structure of action path:"
        ls -la ${{ github.action_path }} || echo "Cannot access action path"
        echo "\nDirectory structure of workspace:"
        ls -la ${{ github.workspace }} || echo "Cannot access workspace"
        echo "\nFull directory structure:"
        find /home/runner/work/_actions -type f || echo "Cannot access actions directory"

    - name: Copy scripts to workspace
      shell: sh
      run: |
        mkdir -p ${{ github.workspace }}/scripts
        cp ${{ github.action_path }}/scripts/* ${{ github.workspace }}/scripts/ || echo "Failed to copy scripts"
        chmod +x ${{ github.workspace }}/scripts/*.sh || echo "Failed to make scripts executable"

    - name: Run setup script
      shell: sh
      run: |
        ${{ github.workspace }}/scripts/setup.sh \
          "${{ inputs.scan_id }}" \
          "${{ inputs.denat_url }}" \
          "${{ inputs.pse_url }}" \
          "${{ github.repository }}" \
          "${{ github.run_id }}" \
          "${{ github.run_attempt }}" \
          "${{ github.workflow }}" \
          "${{ github.job }}" \
          "${{ github.sha }}" \
          "${{ github.ref_name }}"

    - name: Register cleanup
      shell: sh
      run: |
        echo "#!/bin/sh" > /cleanup.sh
        echo "${{ github.workspace }}/scripts/cleanup.sh \
          '${{ github.repository }}' \
          '${{ github.run_id }}' \
          '${{ github.run_attempt }}' \
          '${{ github.run_result }}'" >> /cleanup.sh
        chmod +x /cleanup.sh
        trap "/cleanup.sh" EXIT
