name: 'InvisiRisk PSE Action'
description: 'GitHub Action for InvisiRisk PSE integration'
inputs:
  scan_id:
    description: 'Scan ID for the InvisiRisk PSE'
    required: true
  denat_url:
    description: 'URL to download denat tool'
    required: true
  pse_url:
    description: 'URL to download PSE proxy'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Setup scripts
      shell: sh
      run: |
        # Create scripts directory
        mkdir -p ${{ github.action_path }}/scripts
        
        # Move scripts to the correct location
        mv ${{ github.action_path }}/setup.sh ${{ github.action_path }}/scripts/
        mv ${{ github.action_path }}/cleanup.sh ${{ github.action_path }}/scripts/
        
        # Make scripts executable
        chmod +x ${{ github.action_path }}/scripts/*.sh

    - name: Run setup script
      shell: sh
      run: |
        ${{ github.action_path }}/scripts/setup.sh \
          "${{ inputs.scan_id }}" \
          "${{ inputs.denat_url }}" \
          "${{ inputs.pse_url }}" \
          "${{ github.repository }}" \
          "${{ github.run_id }}" \
          "${{ github.run_attempt }}" \
          "${{ github.workflow }}" \
          "${{ github.job }}" \
          "${{ github.sha }}" \
          "${{ github.ref_name }}"

    - name: Register cleanup
      shell: sh
      run: |
        # Create cleanup script
        echo "#!/bin/sh" > /cleanup.sh
        echo "${{ github.action_path }}/scripts/cleanup.sh \
          '${{ github.repository }}' \
          '${{ github.run_id }}' \
          '${{ github.run_attempt }}' \
          '${{ github.run_result }}'" >> /cleanup.sh
        chmod +x /cleanup.sh
        # Register cleanup to run on exit
        trap "/cleanup.sh" EXIT
