name: Build and Test

on:
  push:
    branches: [ main ]
    paths-ignore:
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Make scripts executable
      run: |
        chmod +x scripts/*.sh
        git config --local user.email "github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add scripts/
        git commit -m "chore: make scripts executable" || echo "No changes to commit"
        git push

    - name: Test scripts
      run: |
        # Basic syntax check for shell scripts
        for script in scripts/*.sh; do
          echo "Checking $script"
          sh -n "$script"
        done

    - name: Create Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v0.19.0
        files: |
          scripts/*
          action.yml
        generate_release_notes: true
